### ISSUE TITLE
Website doesn't work on Safari browser

### ISSUE THREAD

**Issue by lewisfm** [Lodestone-Team/landing-page#47]
# Intention:

The lodestone.cc website doesn't load on Safari, because it uses Regex features that aren't supported on the browser.

Console:
![42648](https://user-images.githubusercontent.com/75394401/212805971-d354ce36-fdd2-42b3-8614-af4943c4ceb9.png)
Website:
![51433](https://user-images.githubusercontent.com/75394401/212806067-93fe5d04-96f6-41f1-91a0-8badba293d03.png)

Notes:
- While the [Safari Tech Preview](https://developer.apple.com/safari/technology-preview/) does allow Regex lookbehinds, this feature isn't stable yet and it'll probably be a while before it is.
- https://caniuse.com/js-regexp-lookbehind
- Looking at the minified source it appears to be related to some kind of TOML-parsing library

# Why is it necessary:

It makes the website unusable for anyone using Safari on their phone or computer.

**Comment by Ynng** [comment]
Thanks for leaving an issue, but unfortunately, I'll have to close it as it's a [known issue](https://github.com/Lodestone-Team/lodestone/wiki/Known-Issues) and already tracked in https://github.com/Lodestone-Team/lodestone/issues/101.

The toml language support for Monaco editor was copied from [fnky's codesandbox](https://codesandbox.io/s/fu64h?file=/src/Editor/languages/toml.ts) and we aren't very familiar with it either, so this might take some time to solve.

Otherwise, we'll disable toml in 0.4.1 which should release in around 2 weeks, and wait for lookbehind to make its way into stable Safari.
